### ISSUE TITLE
Documentation / Tutorial

### ISSUE THREAD

**Issue by lopippo** [uweschmitt/emzed2#23]
Greetings, 

I would like to have a pointer to a documentation file or tutorial. Would this be possible ?
Thank you very much.

lopippo

**Comment by uweschmitt** [comment]
Regrettably the website is currently down

**Comment by lopippo** [comment]
Maybe you have a backup copy of that documentation somewhere as a zip file ?
Thank you
lopippo

**Comment by uweschmitt** [comment]
The code is here: https://github.com/uweschmitt/emzed2/tree/master/website

Regrettably building the html files only works partially right now. The code is outdated. Sorry.

**Comment by lopippo** [comment]
Thank you very much. I'll try to make something with the code.

**Comment by uweschmitt** [comment]
But I'm currently working on emzed3 which we hope to release in summer.
