### ISSUE TITLE
Fix the urls !

### ISSUE THREAD

**Issue by lopippo** [uweschmitt/emzed2#24]
Please, do fix the bad urls on this site. They give a deplorable image of the project.
Thank you for your endeavours in Free Software.

lopippo

**Comment by uweschmitt** [comment]
You mean broken links?

**Comment by lopippo** [comment]
Of course !

Rewrite of emzed framework for LCMS data analysis http://emzed.ethz.ch
and

This is the successor of http://github.com/uweschmitt/emzed. Look at http://emzed.ethz.ch for more information.

**Comment by uweschmitt** [comment]
Ah, here in the repository? Thanks, will fix this.
