### ISSUE TITLE
emzed3 status

### ISSUE THREAD

**Issue by lopippo** [uweschmitt/emzed2#28]
Greetings, 
in messages that we exchanged earlier this year, you stated that emzed3 was going to be available in summer 2020. Is there any chance this turned out to be reality?

Sincerely,
Filippo Rusconi

**Comment by uweschmitt** [comment]
Hi,
we did not release emzed officially but work is almost finished and you can start using emzed. Have a look at https://emzed.ethz.ch.

Documentation is still lacking, what OS are you using?

**Comment by lopippo** [comment]
Greetings,

thank you for your answer. I'm running Debian GNU/Linux.I would be interested in packaging that software once the docs are ok (I am a Debian Developer). 

Sincerely,
Filippo
